### ISSUE TITLE
Execution of docker-compose up on Windows 10

### ISSUE THREAD

**Issue by mauroIstat** [InseeFr/ARC#56] opened 2020-07-28 13:36 UTC
Dear ARC Team,

I am trying to install ARC on a Windows machine. I execute the 'docker-compose up' command, but I get the following error message:
`Step 8/15 : ARG LOG_PATH=logs/log-arc.log
 ---> Running in d175228b6d89
Removing intermediate container d175228b6d89
 ---> 3e420a404f9b
Step 9/15 : ARG LOG_LEVEL=ERROR
 ---> Running in 67e1109380ac
Removing intermediate container 67e1109380ac
 ---> fa0955e40c84
Step 10/15 : ARG LOG_SETTINGS=fr/insee/config/log4j.xml
 ---> Running in 1911904ebd8f
Removing intermediate container 1911904ebd8f
 ---> ed1df1c30c6a
Step 11/15 : COPY . /usr/src/app/
 ---> c27f84c77339
Step 12/15 : RUN chmod +x usr/src/app/script.sh && usr/src/app/script.sh
 ---> Running in 1f9f3cc346c4
/bin/sh: usr/src/app/script.sh: not found
ERROR: Service 'app' failed to build: The command '/bin/sh -c chmod +x usr/src/app/script.sh && usr/src/app/script.sh' returned a non-zero code: 127`
![arc-docker-compose](https://user-images.githubusercontent.com/22342712/88672763-1fa33080-d0e8-11ea-88fe-c09534252f7d.png)

**Comment by pierre-le-corre** [comment] 2020-08-17 14:48
It seems that script.sh fails with "command not found" for some reason, somewhere before line 11. 
I can't reproduce the issue with Ubuntu, I still need to try on Windows.
What version of Docker and Docker Compose are you running ?

**Comment by mauroIstat** [comment] 2020-08-18 12:31
Here we go,

docker version: 19.03.12
docker-compose version: 1.26.2

**Comment by pierre-le-corre** [comment] 2020-08-19 12:08
Ok, I might have it. I can reproduce the issue if I switch the line-endings in script.sh to Windows-style line endings (CRLF).

Could you check that the line endings are strictly Unix-style (LF) in script.sh on your system ? Depending on your config, git might have switched it to CRLF.

**Comment by mauroIstat** [comment] 2020-08-19 13:05
![arc-script](https://user-images.githubusercontent.com/22342712/90638163-49560000-e22d-11ea-8125-7520a20e2cb2.png)

I think that git switched to CRLF

**Comment by pierre-le-corre** [comment] 2020-08-19 14:58
Yup, this it it.

This is likely related to the git config option `core.autocrlf`. There is some doc [here](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting%20and%20Whitespace).

This won't fix the issue, but you may want to switch off autocrlf for ARC. Inside your local repo, you can run `git config core.autocrlf false`. You can set it globally but this will impact all your git repos (`git config --global core.autocrlf false`).

The file itself is correctly commited with Unix-style line endings. To fix the issue on your side, you can fix the line endings in script.sh by switching them back to Unix-style from Windows-style. I'm not sure what tools you have or what's your setup, but [one common way to do on Windows is with Notepad++](https://notepadunix2dos.info/).

**Comment by pierre-le-corre** [comment] 2020-08-24 06:36
Great if the script.sh issue is fixed. Actually, I think there might be a better way to do it than to force every Windows user to clean it on their side, I am looking into it.

Regarding your new error, are you running the most recent ARC commit ? I'm not sure, but I think this is a bug that has been fixed in early August by @Nolife999.

**Closed** 2021-03-15 21:22 UTC
